### PR TITLE
fixing a few bugs in model.py

### PR DESCRIPTION
**Pull request by peasant98**
This PR fixes a few bugs in the code to work with nerfstudio and the recent versions of gsplat.

### CODE REVIEW

**Comment by RogerQi** [comment]
Thank you for your PR! I will set up a new conda env to test in the next few days (or the next few hours). If it works on the latest version, I will merge it.

**Comment by RogerQi** [comment]
I confirmed that the old implementation doesn't work with the latest NS/gsplat. I am migrating to a new branch with your fix and some misc updates.

**Comment by geyang** [comment]
Thank you both!

**Comment by peasant98** [comment]
Glad to help!

**Pull request merged**
